import type { LucideIcon } from 'lucide-react';
import { Map, Landmark, Swords, Drama, Sparkles, Flame, Coins, ScrollText, User, Trees, Mountain, UserCircle2, Ghost, Sword, Castle, Map as MapIcon, Moon, Cloud, Snowflake } from 'lucide-react';


export interface FruitField {
  id: string;
  label: string;
  type: 'text' | 'textarea' | 'select';
  ph?: string;
  opts?: string[];
}

export interface FruitGuide {
  min: string;
  ref: string;
  steps: string[];
  closing?: string;
}

export interface Fruit {
  id: number;
  num: string;
  name: string;
  desc: string;
  Icon: LucideIcon;
  icon: string;
  gradient: string;
  fields: FruitField[];
  chips: string[];
  guide: FruitGuide;
}

export interface GalleryImage {
  id: string;
  src: string;
  name: string;
  cat: string;
  /** 'unsorted' = generated by AI, awaiting user triage. Defaults to 'kept' for manual uploads. */
  status?: 'unsorted' | 'kept';
}

export type MethodType = 'top-down' | 'bottom-up';
export type TabType = 'construir' | 'codex' | 'galeria' | 'escrever';

export const CODEX_ENTRY_TYPES = [
  { id: 'personagem', label: 'Personagem', icon: 'User' },
  { id: 'lugar', label: 'Lugar', icon: 'Castle' },
  { id: 'item', label: 'Item', icon: 'Swords' },
  { id: 'criatura', label: 'Criatura', icon: 'Flame' },
  { id: 'evento', label: 'Evento', icon: 'ScrollText' },
  { id: 'cultura', label: 'Cultura', icon: 'Drama' },
] as const;

export type CodexEntryType = typeof CODEX_ENTRY_TYPES[number]['id'];

export interface AppState {
  worldName: string;
  db: Record<number, Record<string, string>>;
  currentFruit: number;
  method: MethodType;
  gallery: GalleryImage[];
  activeTab: TabType;
  apiKey: string;
  generatedPrompt: string;
  currentSaveId: string;
}

export const GALLERY_CATEGORIES = [
  'Geral', 'Mapa do Mundo', 'Personagens', 'Criaturas',
  'Arquitetura', 'Paisagens', 'Artefatos', 'Cultura'
];

export const FRUITS: Fruit[] = [
  {
    id: 0, num: '1º Fruto', name: 'Mapa do Mundo', Icon: Map, icon: '',
    gradient: 'from-blue-900 via-cyan-900 to-teal-900',
    desc: 'O mapa é o chão do seu universo — geografia, rotas e fronteiras que conectam tudo.',
    fields: [
      { id: 'continents', label: 'Crie uma Região', type: 'textarea', ph: 'Descreva uma região: clima, terreno, identidade. Ex: "Serra dos Véus — montanhosa, fria, isolada por neblina eterna."' },
      { id: 'climate', label: 'Crie uma Rota ou Fronteira', type: 'textarea', ph: 'Uma rota comercial, militar ou fronteira de tensão. Quem a controla? Por que é disputada?' },
      { id: 'landmarks', label: 'Crie um Local Icônico', type: 'textarea', ph: 'Um lugar que todos conhecem pelo nome. Onde fica? O que o torna lendário?' },
    ],
    chips: ['Criar uma região com conflito', 'Sugerir nome para esta região', 'Desenvolver uma rota perigosa', 'Criar uma fronteira disputada'],
    guide: {
      min: 'O mapa é muito mais do que um desenho bonito — ele é o alicerce do seu universo. Cada montanha, rio e deserto existe por uma razão: montanhas bloqueiam exércitos e isolam culturas, rios são estradas naturais que definem onde surgem cidades, e desertos criam fronteiras que nenhum tratado político consegue.\n\nPense no mapa como a "planta baixa" da sua narrativa. Se seu protagonista precisa viajar de um reino a outro, o terreno entre eles vai ditar o tempo, os perigos e os encontros da jornada. Cidades surgem em portos, cruzamentos e vales férteis — nunca no meio do nada sem motivo.\n\nUse este fruto para criar regiões com identidade própria (clima, terreno, recursos), traçar rotas comerciais e militares que conectam ou dividem povos, e marcar locais icônicos que o leitor vai lembrar pelo nome. Cada entrada aqui pode se tornar uma ficha detalhada no Codex.',
      ref: 'Westeros — George R. R. Martin (As Crônicas de Gelo e Fogo)\n\nMartin não desenhou um mapa aleatório — ele usou a geografia como motor de narrativa:\n\n• A Muralha ao Norte não é só uma construção épica: é uma barreira psicológica. Tudo ao norte dela é "o desconhecido", o que justifica o medo e a negligência dos sulistas.\n\n• Dorne, isolada por montanhas e deserto, desenvolveu uma cultura completamente diferente do resto de Westeros: mais liberal, com leis de herança igualitárias e resistência feroz a invasores.\n\n• O Gargalo (The Neck) é um pântano que funciona como defesa natural do Norte — por isso os Stark conseguiram manter independência por milênios.\n\n• Porto Real fica onde fica porque Aegon desembarcou ali: a capital não surgiu por ser o melhor local, mas por ser o ponto de conquista. Isso gera tensão política constante.\n\nMartin confessou que inverteu o mapa da Irlanda e o colou ao Reino Unido como base geográfica — e depois ajustou para servir à história.',
      steps: [],
      closing: 'Ao tomar deste fruto, o firmamento do seu Mundo será materializado.',
    },
  },
  {
    id: 1, num: '2º Fruto', name: 'Sistema Político', Icon: Landmark, icon: '',
    gradient: 'from-indigo-900 via-purple-900 to-blue-900',
    desc: 'Quem manda, como manda e por que alguém quer derrubar quem manda. Combustível de trama.',
    fields: [
      { id: 'govtype', label: 'Crie um Governo ou Facção', type: 'textarea', ph: 'Forma de governo ou facção política: como funciona, quem está no topo, como o poder é mantido.' },
      { id: 'conflict', label: 'Crie uma Tensão Política', type: 'textarea', ph: 'Algo prestes a explodir: segredo político, facção crescendo às sombras, lei reveladora do poder.' },
      { id: 'laws', label: 'Crie uma Lei ou Punição', type: 'textarea', ph: 'Uma lei que mostra como o poder realmente funciona. Ex: "Questionar a linhagem real em público é punido com a remoção da língua."' },
    ],
    chips: ['Criar um sistema de governo original', 'Desenvolver facção com agenda secreta', 'Gerar uma lei que revela o tom do poder', 'Criar uma conspiração política'],
    guide: {
      min: 'Política não é só "quem é o rei". É sobre como o poder funciona no dia a dia: quem cobra impostos, quem julga crimes, quem decide ir à guerra e por quê. Um sistema político bem construído é o maior gerador de conflito do seu mundo.\n\nPense em camadas: há o poder oficial (o trono, o senado, o conselho) e o poder real (quem sussurra no ouvido do rei, quem controla o ouro, quem comanda os exércitos). A tensão entre essas camadas é combustível narrativo puro.\n\nLeis revelam valores — e hipocrisia. Se a lei proíbe magia mas o rei tem um mago conselheiro, isso diz tudo sobre como o poder funciona. Crie governos, facções com agendas próprias e leis que mostrem as contradições do sistema. Cada facção pode virar uma entrada no Codex.',
      ref: 'Sistemas de Poder em Grandes Narrativas\n\n• Gondor vs. Rohan (O Senhor dos Anéis): Tolkien mostra dois modelos — Gondor é uma monarquia burocrática em decadência (governada por um Regente que se recusa a ceder o trono), enquanto Rohan é uma monarquia guerreira onde o rei cavalga na linha de frente. A diferença cultural nasce do sistema político.\n\n• O Império Galáctico (Star Wars): Lucas se inspirou na queda da República Romana. Palpatine não tomou o poder à força — foi eleito Chanceler, acumulou "poderes emergenciais" durante as Guerras Clônicas e transformou a República em Império com aplausos do Senado. É um estudo de como tiranos surgem de dentro do próprio sistema.\n\n• O Covenant (Halo): Uma teocracia liderada pelos Profetas, onde a casta sacerdotal detém poder absoluto sobre raças guerreiras (Sangheili, Jiralhanae) em nome de uma "Grande Jornada" sagrada. Quando a mentira fundadora é exposta, a aliança racha em guerra civil — mostrando a fragilidade do poder baseado em fé cega.\n\n• Westeros: O Trono de Ferro é literalmente desconfortável de propósito — Aegon o forjou com as espadas dos inimigos derrotados para lembrar que governar nunca deve ser confortável. Mas isso não impede que cada ocupante abuse do poder de formas diferentes.',
      steps: [],
      closing: 'Ao tomar deste fruto, os fios do destino começarão a se ordenar diante do caos.',
    },
  },
  {
    id: 2, num: '3º Fruto', name: 'Fatos Históricos', Icon: Swords, icon: '',
    gradient: 'from-amber-900 via-red-900 to-orange-900',
    desc: 'História, eras e calendário transformam seu mundo em consequência. O presente carrega marcas do passado.',
    fields: [
      { id: 'origin', label: 'Crie um Evento Histórico', type: 'textarea', ph: 'Um evento do passado que ainda marca o presente: fundação, guerra, queda ou descoberta.' },
      { id: 'turning', label: 'Crie uma Figura ou Relíquia', type: 'textarea', ph: 'Uma pessoa do passado cujo nome ainda move pessoas, ou um objeto/documento que sobreviveu ao tempo.' },
      { id: 'present', label: 'Crie o Ponto de Partida', type: 'textarea', ph: 'Em que momento da linha do tempo sua narrativa começa? O que acabou de acontecer que todos comentam?' },
    ],
    chips: ['Criar calendário', 'Criar evento histórico fundador', 'Desenvolver relíquia com significado oculto', 'Expandir uma figura lendária', 'Conectar passado ao conflito presente'],
    guide: {
      min: 'A história do seu mundo é o que transforma cenário em consequência. Cada guerra, descoberta ou catástrofe do passado deixa cicatrizes visíveis no presente: ruínas que ninguém ousa reconstruir, linhagens reais que carregam culpa ancestral, fronteiras que existem por causa de um tratado de 300 anos.\n\nNão crie uma linha do tempo enciclopédica — crie eventos que ainda importam. A pergunta-chave é: "Isso afeta alguém vivo na história?" Se a resposta for não, o evento é decorativo. Se for sim, é narrativa.\n\nPense em três camadas temporais: a origem (mitos fundadores, como o mundo começou), os pontos de virada (guerras, descobertas, quedas de impérios) e o presente imediato (o que acabou de acontecer que coloca tudo em movimento). Figuras históricas e relíquias do passado funcionam como âncoras emocionais — o leitor entende o peso do presente quando conhece o passado.',
      ref: 'The Elder Scrolls — Bethesda (Tamriel)\n\nA franquia Elder Scrolls é referência mundial em história de worldbuilding porque cada jogo se passa em uma era diferente, mas os eventos anteriores sempre reverberam:\n\n• A Guerra dos Dragões (Era Merética): Aconteceu milênios antes de Skyrim, mas os dragões retornam no jogo — e os jogadores descobrem que a profecia do Dragonborn nasceu desse conflito original.\n\n• Tiber Septim / Talos: Um homem que conquistou todo o continente e, após a morte, foi elevado a deus. Gerações depois, o Domínio Aldmeri proíbe seu culto — e esse ato político é o pivô central de Skyrim. Um evento de 400 anos atrás move a guerra civil do presente.',
      steps: [],
      closing: 'Ao tomar deste fruto, linhas do tempo são criadas e possibilidades se abrem.',
    },
  },
  {
    id: 3, num: '4º Fruto', name: 'Cultura', Icon: Drama, icon: '',
    gradient: 'from-rose-900 via-pink-900 to-fuchsia-900',
    desc: 'Cultura é identidade: o que faz um povo parecer real e inesquecível.',
    fields: [
      { id: 'beliefs', label: 'Crie um Valor ou Ritual', type: 'textarea', ph: 'Um valor central, ritual ou festival que define a identidade desse povo. O que praticam vs. o que pregam?' },
      { id: 'customs', label: 'Crie um Tabu ou Costume', type: 'textarea', ph: 'Algo que esse povo simplesmente não faz — ou um detalhe cotidiano: vestuário, cumprimento, forma de tratar estranhos.' },
      { id: 'items', label: 'Crie um Item Cultural', type: 'textarea', ph: 'Vestimenta cerimonial, arma tradicional, instrumento musical ou artefato do cotidiano.' },
    ],
    chips: ['Criar valor com contradição oculta', 'Desenvolver ritual com significado profundo', 'Criar um tabu e suas consequências', 'Gerar cena que mostra a cultura em ação'],
    guide: {
      min: 'Cultura é o que faz um povo parecer real e não apenas um nome num mapa. É a diferença entre "eles vivem no Norte" e "eles marcam a pele com cinzas dos ancestrais ao completar 16 anos, porque acreditam que os mortos protegem através da dor".\n\nCultura se constrói em três níveis: o que o povo acredita (valores, religião, superstições), o que o povo faz (rituais, festivais, costumes cotidianos) e o que o povo cria (armas, roupas, música, culinária). O segredo é a contradição — o que pregam vs. o que praticam. Um povo que valoriza honra mas pratica escravidão é mais interessante que um povo "honrado".\n\nDetalhes sensoriais fazem a diferença: como cumprimentam estranhos? O que comem no café da manhã? Qual insulto é imperdoável? Esses micro-detalhes dão ao leitor a sensação de estar dentro do mundo, não lendo sobre ele.',
      ref: 'Avatar: O Último Mestre do Ar — Bryan Konietzko & Michael DiMartino\n\nAvatar é uma masterclass em cultura como worldbuilding porque cada nação é construída com coerência total entre filosofia, estética, luta e modo de vida.',
      steps: [],
      closing: 'Ao tomar deste fruto, povos e raças cantam e dançam ao redor da própria identidade.',
    },
  },
  {
    id: 4, num: '5º Fruto', name: 'Magia & Tecnologia', Icon: Sparkles, icon: '',
    gradient: 'from-violet-900 via-blue-900 to-cyan-900',
    desc: 'O que é possível — e impossível — no seu mundo. Magia e tecnologia criam tensão quando controladas por grupos diferentes.',
    fields: [
      { id: 'magictype', label: 'Tipo de Sistema', type: 'select', opts: ['Magia Dura (regras claras)', 'Magia Suave (misteriosa)', 'Híbrido Magia/Ciência'] },
      { id: 'magicrules', label: 'Crie uma Regra ou Tecnologia', type: 'textarea', ph: 'Uma regra do sistema mágico (custo, limite, risco) ou uma tecnologia/invenção do seu mundo.' },
      { id: 'magicitems', label: 'Crie um Item Mágico ou Tecnológico', type: 'textarea', ph: 'Arma encantada, artefato antigo, dispositivo tecnológico. Poder, origem e custo de uso.' },
    ],
    chips: ['Definir custo e limite de um feitiço', 'Criar item híbrido (tecnologia + magia)', 'Gerar conflito político sobre a magia', 'Desenvolver grupo que rejeita a magia'],
    guide: {
      min: 'Este fruto trata do que é possível — e impossível — no seu universo. Magia e tecnologia são duas faces da mesma moeda: ambas definem os limites do poder, e quem os controla define a política.\n\nA decisão mais importante é: seu sistema é "Duro" (regras claras, custos definidos, consistência lógica) ou "Suave" (misterioso, imprevisível, focado em atmosfera)? Sistemas duros geram tensão tática, sistemas suaves geram admiração e medo.\n\nTodo poder precisa de um custo. Sem custo, não há tensão.',
      ref: 'Game of Thrones — George R. R. Martin\n\nMartin é brilhante porque usa magia dura e suave simultaneamente, em camadas.',
      steps: [],
      closing: 'Ao tomar deste fruto, fantasia e ciência dançam ao redor da existência.',
    },
  },
  {
    id: 5, num: '6º Fruto', name: 'Seres Fantásticos', Icon: Flame, icon: '',
    gradient: 'from-emerald-900 via-green-900 to-teal-900',
    desc: 'Seres que mudam política, história e cultura. Bem construídos, sustentam tramas longas.',
    fields: [
      { id: 'races', label: 'Crie uma Criatura ou Raça', type: 'textarea', ph: 'Origem, aparência, papel no mundo. Como humanos lidam com ele: aliança, medo ou exploração?' },
      { id: 'origin2', label: 'Crie uma Origem ou Relação', type: 'textarea', ph: 'De onde veio esse ser? Como duas espécies se relacionam? Existe preconceito, guerra ou aliança?' },
    ],
    chips: ['Criar criatura com papel político', 'Desenvolver raça com cultura própria', 'Gerar conflito entre espécies', 'Criar ser cuja origem é mistério'],
    guide: {
      min: 'Seres fantásticos não são decoração — são agentes políticos, culturais e narrativos. Um dragão não é interessante porque cospe fogo; é interessante porque sua existência muda a balança de poder, gera cultos religiosos e força civilizações a se adaptarem.\n\nA pergunta fundamental para cada criatura ou raça é: "Como o mundo seria diferente sem ela?" Se a resposta for "igual", o ser é decorativo. Se a resposta for "completamente diferente", você tem algo poderoso.',
      ref: 'Tolkien (O Senhor dos Anéis) & Hajime Isayama (Attack on Titan)\n\nDois extremos que funcionam brilhantemente.',
      steps: [],
      closing: 'Ao tomar deste fruto, a vida fantástica se materializa diante de seus olhos.',
    },
  },
  {
    id: 6, num: '7º Fruto', name: 'Economia', Icon: Coins, icon: '',
    gradient: 'from-yellow-900 via-amber-900 to-orange-900',
    desc: 'Economia explica rotas, guerras, desigualdades e alianças do seu mundo.',
    fields: [
      { id: 'currency', label: 'Crie um Sistema ou Recurso', type: 'textarea', ph: 'Moeda, forma de troca ou recurso valioso. Quem controla? Onde fica? Por que é disputado?' },
      { id: 'classes', label: 'Crie uma Dinâmica Econômica', type: 'textarea', ph: 'Classes sociais, rotas comerciais ou mercado negro. Quem faz o trabalho pesado e quem lucra?' },
    ],
    chips: ['Criar recurso raro e quem o controla', 'Desenvolver rota comercial com perigos', 'Gerar crise econômica em andamento', 'Criar guilda com agenda própria'],
    guide: {
      min: 'Economia é o que explica por que guerras acontecem, por que rotas são perigosas, por que alguns vivem em palácios e outros em favelas. Não precisa ser complexa — precisa ser sentida.',
      ref: 'O Nome do Vento — Patrick Rothfuss\n\nRothfuss faz algo raro: transforma dinheiro em ferramenta narrativa constante e emocionalmente carregada.',
      steps: [],
      closing: 'Ao tomar deste fruto, moedas de ouro cintilam e sibilam: o bem e o mal lutam por poder.',
    },
  },
  {
    id: 7, num: '8º Fruto', name: 'Linguagem', Icon: ScrollText, icon: '',
    gradient: 'from-stone-900 via-neutral-900 to-zinc-900',
    desc: 'Consistência de nomes, termos e expressões que fazem o mundo parecer real.',
    fields: [
      { id: 'languages', label: 'Crie um Padrão Fonético', type: 'textarea', ph: 'Sons que caracterizam os nomes de um povo. 2-3 regras. Ex: "Nomes do norte terminam em consoante curta (Varn, Aste)."' },
      { id: 'writing', label: 'Crie Termos ou Expressões', type: 'textarea', ph: 'Saudação, insulto, título ou expressão idiomática com significado cultural. Ex: "Que o fogo te encontre antes do frio."' },
    ],
    chips: ['Criar padrão fonético para um povo', 'Gerar termos culturais com significado', 'Criar expressão idiomática reveladora', 'Desenvolver variação de dialeto'],
    guide: {
      min: 'Linguagem é o detalhe que separa mundos genéricos de mundos que parecem reais. Você não precisa criar um idioma completo — precisa criar consistência.',
      ref: 'Tolkien — O Pai da Linguística Ficcional\n\nTolkien não criou línguas para seus livros — ele criou livros para suas línguas.',
      steps: [],
      closing: 'Ao tomar deste fruto, palavras ganham vida e culturas recebem a voz de muitas almas.',
    },
  },
  {
    id: 8, num: '9º Fruto', name: 'Mitologia', Icon: Sparkles, icon: '',
    gradient: 'from-sky-900 via-indigo-900 to-violet-900',
    desc: 'Origem, propósito e destino do mundo. Explica o inexplicável e gera conflito.',
    fields: [
      { id: 'gods', label: 'Crie uma Divindade ou Mito', type: 'textarea', ph: 'Um deus, espírito ou mito de criação: domínio, personalidade, como influencia a vida real.' },
      { id: 'afterlife', label: 'Crie uma Crença ou Relíquia', type: 'textarea', ph: 'Crença sobre o pós-morte, prática religiosa cotidiana, ou objeto/lugar sagrado disputado.' },
    ],
    chips: ['Criar mito de criação com tom moral', 'Desenvolver heresia e seus seguidores', 'Gerar profecia que move a trama', 'Criar relíquia com disputa política'],
    guide: {
      min: 'Mitologia é a camada mais profunda do worldbuilding — é onde você responde as perguntas que os habitantes do seu mundo não conseguem responder sozinhos.',
      ref: 'Mitologia Nórdica — Neil Gaiman / Edda Poética\n\nA mitologia nórdica é uma das mais influentes na fantasia moderna.',
      steps: [],
      closing: 'Ao tomar deste fruto, o destino do seu mundo estará traçado nas linhas da eternidade.',
    },
  },
  {
    id: 9, num: '10º Fruto', name: 'Personagens', Icon: User, icon: '',
    gradient: 'from-slate-900 via-gray-900 to-zinc-900',
    desc: 'O ponto de contato do leitor com o mundo. Nascem dele e também o transformam.',
    fields: [
      { id: 'protagonist', label: 'Crie um Protagonista ou Antagonista', type: 'textarea', ph: 'O que quer, o que teme, qual ferida do passado distorce sua visão. Virtude + falha + decisão difícil.' },
      { id: 'supporting', label: 'Crie um Aliado, Rival ou Arco', type: 'textarea', ph: 'Um aliado que questiona, um rival que espelha, ou um arco de transformação: como começa e termina.' },
    ],
    chips: ['Desenvolver a ferida do protagonista', 'Criar antagonista que o leitor quase defende', 'Gerar conflito entre aliados', 'Definir arco de transformação'],
    guide: {
      min: 'Personagens são o ponto de contato emocional entre o leitor e o seu mundo. O leitor não se importa com a geopolítica de Westeros — se importa com Jon Snow tentando fazer a coisa certa num mundo que pune quem faz a coisa certa.',
      ref: 'George R. R. Martin — Personagens "Cinzas"\n\nMartin revolucionou a fantasia ao recusar personagens puramente bons ou maus.',
      steps: [],
      closing: 'Ao tomar deste fruto, a alma do seu mundo despertará através dos olhos de quem o habita.',
    },
  },
  {
    id: 10, num: 'Último Fruto', name: 'A Sua Narrativa', Icon: Trees, icon: '',
    gradient: 'from-blue-900 via-indigo-900 to-purple-900',
    desc: 'Conecte tudo em história. O mundo age sobre as pessoas e elas causam reação em cadeia.',
    fields: [
      { id: 'premise', label: 'Crie a Premissa e Tema', type: 'textarea', ph: 'Quem é o protagonista, o que quer, o que o impede. E a pergunta central: "Até onde a lealdade justifica a traição?"' },
      { id: 'tone', label: 'Tom, Gênero e Cena de Abertura', type: 'textarea', ph: 'Dark fantasy épico? Aventura com humor ácido? Onde e como começa? A primeira cena deve criar uma pergunta.' },
    ],
    chips: ['Escrever a premissa em uma frase', 'Definir a pergunta-tema', 'Criar a cena de abertura', 'Gerar sinopse de 3 parágrafos'],
    guide: {
      min: 'Este é o fruto que une todos os outros. Até agora você construiu o cenário — agora é hora de transformar cenário em história.',
      ref: 'O "Mundo Autorregente" — Princípio de Brandon Sanderson & N.K. Jemisin\n\nOs melhores worldbuilders modernos compartilham um princípio: o mundo serve à história, não o contrário.',
      steps: [],
      closing: 'Ao tomar deste fruto, a sua voz ecoará por mundos que agora possuem vida própria.',
    },
  },
];

// Fruit names for gallery cataloging
export const FRUIT_CATEGORIES = FRUITS.map(f => `Fruto: ${f.name}`);

export const CATEGORIES = [
  'Todos', ...GALLERY_CATEGORIES, ...FRUIT_CATEGORIES
];

// Top-down: world → details → characters (default order)
export const TOP_DOWN_ORDER = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

// Bottom-up: characters → local → expand world
export const BOTTOM_UP_ORDER = [9, 10, 0, 3, 4, 5, 8, 2, 1, 6, 7];

// Recommended Codex entry type per fruit (Idriel guidance)
export type RecommendedType = 'ficha' | 'artigo' | 'both';
export const FRUIT_RECOMMENDED_TYPE: Record<number, RecommendedType> = {
  0: 'ficha',
  1: 'artigo',
  2: 'artigo',
  3: 'both',
  4: 'artigo',
  5: 'ficha',
  6: 'artigo',
  7: 'artigo',
  8: 'artigo',
  9: 'ficha',
  10: 'artigo',
};

export function getOrderedFruits(method: MethodType): Fruit[] {
  const order = method === 'top-down' ? TOP_DOWN_ORDER : BOTTOM_UP_ORDER;
  return order.map(id => FRUITS[id]);
}

export const METHOD_DESCRIPTIONS: Record<MethodType, { title: string; desc: string }> = {
  'top-down': {
    title: 'Cima para Baixo',
    desc: 'Começa pela visão geral — continentes, nações, história — e vai detalhando até personagens e cenas.',
  },
  'bottom-up': {
    title: 'Baixo para Cima',
    desc: 'Começa pelos personagens e um local central, expandindo o mundo conforme a história exige.',
  },
};

import styleEpicFantasy from '@/assets/style-thumbs/epic-fantasy.jpg';
import styleDarkFantasy from '@/assets/style-thumbs/dark-fantasy.jpg';
import styleAnime from '@/assets/style-thumbs/anime.jpg';
import styleRealistic from '@/assets/style-thumbs/realistic.jpg';
import styleMedieval from '@/assets/style-thumbs/medieval-illustration.jpg';
import styleConcept from '@/assets/style-thumbs/concept-art.jpg';
import styleWatercolor from '@/assets/style-thumbs/watercolor.jpg';
import styleSteampunk from '@/assets/style-thumbs/steampunk.jpg';
import styleCosmicHorror from '@/assets/style-thumbs/cosmic-horror.jpg';

export interface StyleMeta {
  label: string;
  description: string;
  image: string;
  promptHint: string;
}

export const STYLE_META: StyleMeta[] = [
  { label: 'Fantasia épica',           description: 'Reinos majestosos, luz dourada, tom mítico.', image: styleEpicFantasy,   promptHint: 'high fantasy epic painting, majestic, cinematic lighting' },
  { label: 'Dark Fantasy (sombrio)',   description: 'Atmosfera gótica, tensa e melancólica.',      image: styleDarkFantasy,   promptHint: 'dark fantasy, gothic, moody, desaturated palette' },
  { label: 'Anime / Mangá',            description: 'Cel-shading vibrante ao estilo japonês.',     image: styleAnime,          promptHint: 'anime manga style, cel shading, vibrant colors' },
  { label: 'Realista / Fotográfico',   description: 'Fotografia cinematográfica hiper-detalhada.', image: styleRealistic,      promptHint: 'photorealistic, cinematic, 85mm film photo, ultra detailed' },
  { label: 'Ilustração medieval',      description: 'Manuscrito iluminado com folha de ouro.',     image: styleMedieval,       promptHint: 'medieval illuminated manuscript, gold leaf, ornate borders' },
  { label: 'Concept art de videogame', description: 'Pintura digital de estúdios AAA.',            image: styleConcept,        promptHint: 'AAA video game concept art, digital painting, high detail' },
  { label: 'Aquarela / Arte digital',  description: 'Pinceladas suaves e atmosfera onírica.',      image: styleWatercolor,     promptHint: 'watercolor illustration, soft washes, dreamy atmosphere' },
  { label: 'Steampunk',                description: 'Latão vitoriano, engrenagens e vapor.',       image: styleSteampunk,      promptHint: 'steampunk, victorian brass, gears and steam, sepia tones' },
  { label: 'Horror cósmico',           description: 'Entidades incognoscíveis e vazio estelar.',   image: styleCosmicHorror,   promptHint: 'cosmic horror, lovecraftian, eldritch entities, starry void' },
];

export const STYLE_OPTIONS = STYLE_META.map(s => s.label);

export interface OptionMeta {
  label: string;
  description: string;
  icon: LucideIcon;
}
  label: string;
  description: string;
  icon: LucideIcon;
}

export const IMAGE_TYPE_META: OptionMeta[] = [
  { label: 'Cenário / Paisagem',        description: 'Vista ampla de um lugar.',       icon: Mountain },
  { label: 'Personagem (corpo inteiro)',description: 'Figura de pé, completa.',        icon: User },
  { label: 'Retrato de personagem',     description: 'Close no rosto e ombros.',       icon: UserCircle2 },
  { label: 'Criatura / Monstro',        description: 'Bestas e seres fantásticos.',    icon: Ghost },
  { label: 'Objeto / Artefato mágico',  description: 'Item isolado em destaque.',      icon: Sword },
  { label: 'Cidade / Arquitetura',      description: 'Construções e conjuntos.',       icon: Castle },
  { label: 'Batalha / Cena de ação',    description: 'Movimento e conflito.',          icon: Swords },
  { label: 'Mapa / Cartografia',        description: 'Vista de topo com legendas.',    icon: MapIcon },
];

export const IMAGE_TYPE_OPTIONS = IMAGE_TYPE_META.map(o => o.label);

export const TONE_META: OptionMeta[] = [
  { label: 'Épico e grandioso',        description: 'Luz radiante, escala monumental.', icon: Sparkles },
  { label: 'Sombrio e ominoso',        description: 'Sombras densas, presságio.',       icon: Moon },
  { label: 'Místico e etéreo',         description: 'Brumas suaves, luz difusa.',       icon: Cloud },
  { label: 'Quente e acolhedor',       description: 'Tons dourados de fogueira.',       icon: Flame },
  { label: 'Frio e desolado',          description: 'Azuis gélidos, silêncio.',         icon: Snowflake },
  { label: 'Dramático (luz e sombra)', description: 'Contraste teatral chiaroscuro.',   icon: Drama },
];

export const TONE_OPTIONS = TONE_META.map(o => o.label);
