project_id = "jrioksaacinogvknvkpu"

[functions.check-access]
verify_jwt = false

[functions.ai-text]
verify_jwt = false

[functions.ai-image]
verify_jwt = false

[functions.eduzz-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.idriel-import-text]
verify_jwt = false

[functions.ai-image-consistent]
verify_jwt = false

[functions.send-welcome-email]

verify_jwt = false

[functions.demo-login]
verify_jwt = false





[functions.stripe-create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.stripe-billing-portal]
verify_jwt = false
